# Generated by Django 4.2.2 on 2024-02-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=13)),
                ('mobile', models.CharField(max_length=15)),
                ('empcode', models.CharField(max_length=3)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginuser.position')),
            ],
        ),
    ]
